// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC_tadU6BhOu_cc83ET6golpm_8VuOYFY',
    appId: '1:903995555065:web:5a19671dbcba3052a9f628',
    messagingSenderId: '903995555065',
    projectId: 'smooth-talk-ececa',
    authDomain: 'smooth-talk-ececa.firebaseapp.com',
    storageBucket: 'smooth-talk-ececa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCekiz1Lg2PBAQdFePoQKl6zBd52o0Yxak',
    appId: '1:903995555065:android:6446357e4514bdd9a9f628',
    messagingSenderId: '903995555065',
    projectId: 'smooth-talk-ececa',
    storageBucket: 'smooth-talk-ececa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBumiMTCrUG_2o0DU6-8ALZzVAIe8rjc3k',
    appId: '1:903995555065:ios:47103d541fe03848a9f628',
    messagingSenderId: '903995555065',
    projectId: 'smooth-talk-ececa',
    storageBucket: 'smooth-talk-ececa.appspot.com',
    iosBundleId: 'com.example.praktykiProjekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBumiMTCrUG_2o0DU6-8ALZzVAIe8rjc3k',
    appId: '1:903995555065:ios:af7089de5cf335ada9f628',
    messagingSenderId: '903995555065',
    projectId: 'smooth-talk-ececa',
    storageBucket: 'smooth-talk-ececa.appspot.com',
    iosBundleId: 'com.example.praktykiProjekt.RunnerTests',
  );
}
